### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by raphaelbastide** [celiadzc/type-derivation#2]
1. Convert all the fonts in webfonts using [Fontsquirrel](http://www.fontsquirrel.com/tools/webfont-generator). This will allow to render fonts in the browser.
2. After that, each font packs (only the libre ones actually) will need to be added to this repository.
3. Then each box will need to be styled with the correct font.

**Comment by celiadzc** [comment]
Well it's done. There are 2 types that I can't add : 
VirusDeja Vu : it's a kinda strange case. We need to purchase the open source font even if it's 0$. License agreements are particular... I am not sure we can use it. For example : 
- "The Virus Font Software is licenced for use at one (1) location with a maximum of five (5) devices. For example: five (4) CPUs and one (1) printer."
- "Except as permitted herein, you may not modify, adapt, translate, reverse engineer, decompile, disassemble, alter or otherwise copy the Virus Font Software." 
- "You agree that any derivative works created by you from the Virus Font Software, including, but not limited to, software, EPS files, or other electronic works, are considered derivative works and use of the derivative work is subject to the terms and conditions of this Licence Agreement. Derivative works may not be sublicenced, sold, leased, rented, lent, or given away without written permission from Virus."

Gehen font : There is no .ttf file, .only conf files. Font licence seems complicated too. Take a look [here](https://github.com/bbqsrc/gehen-fonts/blob/master/LICENSE).

**Comment by raphaelbastide** [comment]
Thanks! We’ll talk about those issues next time.
Can you please complete the html file for each font [here](https://github.com/celiadzc/type-derivation/blob/master/viewer/index.html#L9)?
For new the font files exists but are not linked to the html file yet. Let me know if you have questions.

**Comment by celiadzc** [comment]
✔ done
